### ISSUE TITLE
Outlook 2016 column/width issues

### ISSUE THREAD

**Issue by jason-murray** [spatie-custom/mailchimp-boilerplate#1]
Hi, firstly thank you so much for open sourcing a mailchimp boilerplate.  It's helped us massively.

I'm having the following issue with display in Outlook 2016 - the column width is restricted and anything in a two column layout is stacked:

<img width="408" alt="screenshot_24_05_2017__10_09" src="https://cloud.githubusercontent.com/assets/9424106/26395784/17c7b2d6-4069-11e7-9ee1-9a1502d5b4d1.png">

Have you experienced this before?

**Comment by willemvb** [comment]
Thanks for your interest!

Unfortunately we can't test for Outlook 2016 yet, since it is not supported as inbox preview platform in Mailchimp for now (and Litmus is a bit pricey for us). 
Says Mailchimp support:

> "... there are no explicit plans to add Outlook 2016 to the list of available views for the Inbox Preview." 

You might want to experiment with the Outlook conditional css blocks at the top, maybe add some `mso 16` styles as well, but I'm afraid I have no real solution at this point.

**Comment by jason-murray** [comment]
Thanks @willemvb for your quick response! Your advice got me on the right track!

I enabled the current fix included for the 'page break bug' on mso16 and the template started to look much better in Outlook 2016, then I had to go through and ensure that there wasn't any nesting of the `flexibleContainer` class as this was causing issues.

Also the buttons were going right against the bottom of their sections ignoring any padding or margin set which I fixed by adding a hacky `<tr><td>&nbsp;</td></tr>` just before the end of the section table, beneath the closed button table.

Only part I couldn't get looking good was the date stuff so dropped that.

I'll send you a postcard!
